alias isstate='python /root/isstate.py'
alias isstart='python /root/isstart.py'
alias isstop='python /root/isstop.py'
alias isversion='python /root/isversion.py'
alias isterminate='python /root/isterminate.py'
alias iskill='python /root/isterminate.py'
alias tomcatstart='/apache/apache-tomcat-8.0.32/bin/startup.sh'
alias tomcatstop='/apache/apache-tomcat-8.0.32/bin/shutdown.sh'